-- 实时同步元数据：按开奖节拍调度 + 审计
ALTER TABLE sync_meta ADD COLUMN latest_expect TEXT;
ALTER TABLE sync_meta ADD COLUMN latest_open_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_meta ADD COLUMN next_due_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_meta ADD COLUMN last_ok_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_meta ADD COLUMN last_inserted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_meta ADD COLUMN last_rows INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_meta ADD COLUMN last_latency_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_meta ADD COLUMN last_audit_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_meta ADD COLUMN audit_rows INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_meta ADD COLUMN audit_diff INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_meta ADD COLUMN audit_fixed INTEGER NOT NULL DEFAULT 0;
