import { test } from 'node:test'
import assert from 'node:assert/strict'
import * as core from '../../public/static/atlas-core.js'

const digits3 = { min:0,max:9,count:3,ordered:true,replacement:true }
const digits5 = { ...digits3,count:5 }
const eleven5 = { min:1,max:11,count:5,ordered:false,replacement:false }
const front = { ...eleven5,max:35 }
const back = { ...eleven5,max:12,count:2 }
const metric = (id, numbers, previous = null, rule = digits3, params = {}) => core.metricValues(id,numbers,previous,rule,params)
const at = (trend, row, metricId, value) => {
  const i = trend.columns.findIndex(c => c.metricId === metricId && c.value === value)
  assert.ok(i >= 0, 'missing metric column ' + metricId + '=' + value)
  return trend.rows[row].cells[i]
}

test('screenshot arithmetic: sums, tails, repeated differences, rounded means and positional attributes', () => {
  // Concrete examples recorded from the supplied screenshots, not outputs generated by this implementation.
  assert.deepEqual(metric('sum',[1,4,5]),[10])
  assert.deepEqual(metric('sum',[0,0,2]),[2])
  assert.deepEqual(metric('tail',[7,8,6]),[1])
  assert.deepEqual(metric('pairDiff',[7,8,6]),[1,1,2])
  assert.deepEqual(metric('sameDiff',[7,8,6]),[1])
  assert.deepEqual(metric('pairDiff',[5,6,5]),[1,0,1])
  assert.deepEqual(metric('diffCount:0',[5,6,5]),[1])
  assert.deepEqual(metric('diffCount:1',[5,6,5]),[2])
  assert.deepEqual(metric('sameDiff',[2,9,9]),[7])
  assert.deepEqual(metric('sameDiff',[5,5,5]),[0])
  assert.deepEqual(metric('diffCount:0',[5,5,5]),[3])
  assert.deepEqual(metric('shape',[5,5,5]),['豹子'])
  assert.deepEqual(metric('shape',[6,6,2]),['组三'])
  assert.deepEqual(metric('shape',[4,3,1]),['组六'])
  assert.deepEqual(metric('pairSum',[7,4,9]).sort((a,b)=>a-b),[11,13,16])
  assert.deepEqual(metric('pairSum',[0,9,1]).sort((a,b)=>a-b),[1,9,10])
  for (const [numbers,expected] of [[[7,4,9],7],[[0,9,1],3],[[0,3,2],2],[[2,9,6],6]]) assert.deepEqual(metric('mean',numbers),[expected])
  assert.deepEqual(metric('head',[9,7,2]),[9])
  assert.deepEqual(metric('tailNumber',[9,7,2]),[2])
  assert.deepEqual(metric('sorted:0',[9,7,2]),[2])
  assert.deepEqual(metric('positionAttr:2',[0,9,1]),['单','小','质','1路'])
  assert.deepEqual(metric('routeCount:0',[3,9,9]),[3])
  assert.deepEqual(metric('routeCount:0',[0,0,2]),[2])
  assert.deepEqual(metric('sumAmplitude',[0,9,1],[7,4,9]),[10])
  assert.deepEqual(metric('sumAmplitude',[0,3,2],[0,9,1]),[5])
  assert.deepEqual(metric('sumAmplitude',[9,7,2],[0,3,2]),[13])
  assert.deepEqual(metric('sumBands',[1,4,4]),[0])
  assert.deepEqual(metric('sumBands',[1,4,5]),[1])
  assert.deepEqual(metric('sumBands',[9,9,1]),[2])
})

test('enumerated universes match independent arithmetic and preserve combination semantics', () => {
  assert.equal(core.candidateSpace(digits3),10*10*10)
  assert.equal(core.candidateSpace(digits5),10*10*10*10*10)
  const eleven = [...core.enumerateCandidates(eleven5)]
  assert.equal(eleven.length,462)
  assert.equal(new Set(eleven.map(x=>x.join(','))).size,462)
  assert.deepEqual(eleven[0],[1,2,3,4,5])
  assert.deepEqual(eleven.at(-1),[7,8,9,10,11])
  assert.ok(eleven.every(a => a.every((n,i) => !i || n > a[i-1])))
  let frontCount=0,frontContainingOne=0,last
  for (const numbers of core.enumerateCandidates(front)) { frontCount++;if(numbers.includes(1))frontContainingOne++;last=numbers }
  assert.equal(frontCount,324632)
  assert.equal(frontContainingOne,46376) // choose the remaining four from 34 independently
  assert.deepEqual(last,[31,32,33,34,35])
  const backCount=[...core.enumerateCandidates(back)].length
  assert.equal(backCount,66)
  assert.equal(frontCount*backCount,21425712)
  assert.equal(core.candidateSpace({min:1,max:3,count:2,ordered:false,replacement:true}),6)
  assert.deepEqual([...core.enumerateCandidates({min:1,max:3,count:2,ordered:false,replacement:true})],[[1,1],[1,2],[1,3],[2,2],[2,3],[3,3]])
  assert.equal([...core.enumerateCandidates({min:1,max:3,count:2,ordered:true,replacement:false})].length,6)
  assert.throws(()=>core.evaluateCandidates({...digits3,count:6}),/过大|50万/)
})

test('screenshot 500 then 256 candidates, inverse and tolerance obey set arithmetic', () => {
  const oddFirst={metricId:'position:0',values:[1,3,5,7,9],minHits:1,maxHits:1}
  const noZeroOrFive={metricId:'numbers',values:[0,5],minHits:0,maxHits:0}
  assert.equal(core.evaluateCandidates(digits3,[oddFirst]).count,500)
  const rules=[oddFirst,noZeroOrFive]
  assert.equal(core.evaluateCandidates(digits3,rules).count,256) // 4 first choices × 8 × 8
  assert.equal(core.evaluateCandidates(digits3,rules,{inverse:true}).count,744)
  assert.equal(core.evaluateCandidates(digits3,rules,{globalTolerance:1}).count,756) // union: 500 + 512 - 256
  assert.equal(core.evaluateCandidates(digits3,[{metricId:'numbers',values:[0,5],minHits:1,maxHits:1,tolerance:1}]).count,992) // reject only 2³ triples entirely from {0,5}
  assert.equal(core.evaluateCandidates(digits3,[{...noZeroOrFive,exclude:true}]).count,488)
  const page=core.evaluateCandidates(digits3,[],{page:2,pageSize:100})
  assert.deepEqual(page.items[0].numbers,[1,0,0])
  assert.deepEqual(page.items.at(-1).numbers,[1,9,9])
})

test('known gaps and unknown observations never inflate consecutive counts or positional omissions', () => {
  assert.equal(core.omissionStats([true,null,true]).maxStreak,1)
  assert.equal(core.omissionStats([false,null,false]).maxMiss,1)
  assert.equal(core.omissionStats([false,null]).currentMiss,null)
  assert.equal(core.omissionStats([true,null,true]).observed,2)
  const records=[
    {period:'p1',numbers:[1,0,0],previousContiguous:null},
    {period:'p2',numbers:[2,0,0],previousContiguous:true},
    {period:'p4',numbers:[3,0,0],previousContiguous:false},
    {period:'p5',numbers:[2,0,0],previousContiguous:true},
  ]
  const trend=core.buildTrend(records,['sumAmplitude','positionOmission:0'],digits3)
  assert.equal(at(trend,0,'sumAmplitude',1).hit,null)
  assert.equal(at(trend,1,'sumAmplitude',1).hit,true)
  assert.equal(at(trend,2,'sumAmplitude',1).hit,null)
  assert.equal(at(trend,2,'positionOmission:0',1).hit,null)
  assert.equal(at(trend,3,'positionOmission:0',1).hit,true)
  const basic=core.buildTrend([
    {period:'p1',numbers:[1,0,0],previousContiguous:null},
    {period:'p3',numbers:[1,0,0],previousContiguous:false},
  ],['sum'],digits3)
  const sumOne=basic.columns.findIndex(c=>c.value===1)
  assert.equal(basic.stats[sumOne].count,2)
  assert.equal(basic.stats[sumOne].maxStreak,1)
  assert.equal(at(basic,1,'sum',2).miss,1)
})

test('long positional omissions use the documented >=300 bucket instead of losing the hit', () => {
  const history=Array.from({length:400},(_,i)=>({period:'p'+i,numbers:[1,0,0],previousContiguous:i?true:null}))
  const values=metric('positionOmission:0',[2,0,0],null,digits3,{historyBefore:history})
  assert.deepEqual(values,[300])
  const trend=core.buildTrend([...history,{period:'last',numbers:[2,0,0],previousContiguous:true}],['positionOmission:0'],digits3)
  assert.equal(at(trend,400,'positionOmission:0',300).hit,true)
  assert.match(core.metricCatalog(digits3).find(m=>m.id==='positionOmission:0').definition,/300/)
})

test('without-replacement amplitude uses the actual sum range and subset observations count once', () => {
  assert.deepEqual(metric('amplitudeAttr',[3,5,8,9,10],[1,2,3,4,5],eleven5),['双','大','合','2路'])
  const anyTwo={...eleven5,count:2}
  const history=[
    {period:'p1',numbers:[1,2,3,4,5],previousContiguous:null},
    {period:'p2',numbers:[2,3,4,5,6],previousContiguous:true},
  ]
  const trend=core.buildTrend(history,['sum','sumAmplitude'],anyTwo)
  assert.equal(trend.rows.length,2)
  assert.equal(at(trend,0,'sum',3).hit,true)
  assert.equal(at(trend,0,'sum',9).hit,true)
  assert.equal(at(trend,0,'sum',15).hit,false)
  const sumSeven=trend.columns.findIndex(c=>c.metricId==='sum'&&c.value===7)
  assert.equal(trend.stats[sumSeven].count,2) // multiple pairs total seven; each draw contributes one hit
  assert.equal(trend.stats[sumSeven].observed,2)
  assert.equal(at(trend,1,'sumAmplitude',1).hit,null)
  const condition={metricId:'numberSet',values:['01,05'],minHits:1,maxHits:1}
  assert.equal(core.matchesRules([1,2,3,4,5],[condition],anyTwo).accepted,true)
  assert.equal(core.matchesRules([2,3,4,5,6],[condition],anyTwo).accepted,false)
  assert.equal(core.matchesRules([1,5],[condition],anyTwo,{inverse:true}).accepted,false)
  assert.equal(core.matchesRules([1,2,3,4,5],[condition],anyTwo,{inverse:true}).accepted,true)
  const ranked=core.evaluateCandidates(anyTwo,[condition],{history:[history[0]],order:'score'})
  assert.equal(ranked.count,1)
  assert.equal(ranked.items[0].score,100)
  assert.match(ranked.definition,/不是命中概率/)
})

test('all reachable values fit their declared metric domains on exhaustive small universes', () => {
  for (const rule of [digits3,eleven5]) {
    const catalog=core.metricCatalog(rule)
    for (const nums of core.enumerateCandidates(rule)) {
      for (const entry of catalog) {
        if(entry.id==='numberSet')continue
        for (const value of metric(entry.id,nums,nums,rule)) {
          assert.ok(entry.values.includes(value),entry.id+' omitted '+value+' for '+nums.join(','))
        }
      }
    }
  }
  for (const nums of [[1,2,3,4,5],[31,32,33,34,35],[1,2,3,34,35],[1,9,17,26,35]]) {
    for (const entry of core.metricCatalog(front)) {
      if(entry.id==='numberSet')continue
      for (const value of metric(entry.id,nums,nums,front)) assert.ok(entry.values.includes(value),entry.id+' omitted '+value)
    }
  }
})

test('malformed position maps are rejected consistently and invalid candidates cannot pass', () => {
  for (const pairs of [[null],[[0,1.5]],[[0,3]],[[0,0]],'bad']) {
    assert.throws(()=>core.metricCatalog(digits3,{pairs}),/跳位|位置|映射/)
    assert.throws(()=>metric('jumpDiff',[1,2,3],null,digits3,{pairs}),/跳位|位置|映射/)
  }
  assert.deepEqual(metric('jumpDiff',[1,2,3],null,digits3,{pairs:[]}),[])
  assert.equal(core.matchesRules([99],[],digits3).accepted,false)
  assert.deepEqual(metric('sum',[1,2,'3']),[])
  assert.throws(()=>core.evaluateCandidates(eleven5,[{metricId:'position:8',values:[1]}]),/不适用/)
})

test('invalid history cannot dilute scores, oversized observation subsets are bounded, and unknown rules stay unknown', () => {
  const selected={metricId:'numberSet',values:['1,2,3']}
  const result=core.evaluateCandidates(digits3,[selected],{history:[{numbers:[1,2,3]},{numbers:[99]}]})
  assert.equal(result.count,1)
  assert.equal(result.items[0].score,100)
  const many=Array.from({length:49},(_,i)=>i+1)
  const rule={min:1,max:49,count:5,ordered:false,replacement:false}
  assert.throws(()=>core.buildTrend([{period:'p1',numbers:many}],['sum'],rule),/50万|观察范围/)
  assert.throws(()=>core.matchesRules(many,[],rule),/50万|观察范围/)
  const missingPrevious={metricId:'sumAmplitude',values:[1],minHits:1,maxHits:1}
  for(const options of [{inverse:true},{globalTolerance:2},{inverse:true,globalTolerance:2}]) {
    const outcome=core.matchesRules([1,2,3],[missingPrevious],digits3,options)
    assert.equal(outcome.known,false)
    assert.equal(outcome.accepted,false)
  }
})


test('zoned DLT full universe returns only the last page of 21,425,712 combinations', () => {
  // C(35,5) = 324632 and C(12,2) = 66 independently; last 12 back pairs are known lexicographically.
  const result=core.evaluateZonedCandidates({front,back},{},{page:214258,pageSize:100});
  assert.equal(result.total,21425712);
  assert.equal(result.frontCount,324632);
  assert.equal(result.backCount,66);
  assert.equal(result.count,21425712);
  assert.equal(result.items.length,12);
  assert.deepEqual(result.items[0].zones,{front:[31,32,33,34,35],back:[7,11]});
  assert.deepEqual(result.items.at(-1).zones,{front:[31,32,33,34,35],back:[11,12]});
  assert.equal(new Set(result.items.map(item=>item.key)).size,12);
  assert.ok(JSON.stringify(result).length<6000,'response must contain a bounded page, not the product');
});

test('independent zone filters have C(34,4) × 11 results and paginate across zone boundaries', () => {
  const rules={front:[{metricId:'numbers',values:[1],minHits:1,maxHits:1}],back:[{metricId:'numbers',values:[12],minHits:1,maxHits:1}]};
  const result=core.evaluateZonedCandidates({front,back},rules,{page:1,pageSize:12});
  assert.equal(result.frontCount,46376);
  assert.equal(result.backCount,11);
  assert.equal(result.count,510136);
  assert.equal(result.total,21425712);
  assert.equal(result.items.length,12);
  assert.deepEqual(result.items[0].zones,{front:[1,2,3,4,5],back:[1,12]});
  assert.deepEqual(result.items[10].zones,{front:[1,2,3,4,5],back:[11,12]});
  assert.deepEqual(result.items[11].zones,{front:[1,2,3,4,6],back:[1,12]});
});
