const {writeFileSync}=require('node:fs');
const {join,resolve}=require('node:path');
module.exports=async function themeSmoke(win,result,dataDir){
 if(!process.argv.includes('--smoke-test')||!process.argv.some(a=>a.startsWith('--data-dir=')&&resolve(a.slice(11))===resolve(dataDir)))throw Error('主题验收必须使用隔离目录');
 const run=s=>win.webContents.executeJavaScript(s,true),delay=ms=>new Promise(r=>setTimeout(r,ms));
 const wait=async s=>{for(let i=0;i<120;i++){if(await run(s))return;await delay(200)}throw Error('主题界面等待超时 '+s)};
 const shot=async name=>{await delay(150);writeFileSync(join(dataDir,name+'.png'),(await win.webContents.capturePage()).toPNG())};
 await win.loadURL('hashplay://app/simulator?source=qkltj:6002');await wait('!!document.querySelector("#p-unit") && !!document.querySelector("#hp-theme-dialog")');
 await wait('!!document.querySelector(".paper-ledger .st-pill.hit")');
 const original=await run('document.querySelector("#p-unit").value');
 await run('document.querySelector("#p-unit").value="0.37";document.querySelector("#hp-theme-toggle").click()');
 const themes=['warm','market','betting','cyber','game','fintech','exchange'],backgrounds=[],contrast=[];
 const ratio=(a,b)=>{const lum=s=>{const rgb=s.replace('#','').match(/../g).map(x=>parseInt(x,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722};const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
 for(const theme of themes){
  await run('document.querySelector(\'[data-theme-choice="'+theme+'"]\').click()');
  const state=await run('({theme:document.documentElement.dataset.theme,unit:document.querySelector("#p-unit").value,pressed:document.querySelectorAll("[data-theme-choice][aria-pressed=true]").length,bg:getComputedStyle(document.body).backgroundColor,hit:getComputedStyle(document.querySelector(".hp-theme-samples .hp-hit")).color,selected:getComputedStyle(document.querySelector(".hp-theme-samples .hp-selected")).color,panel:HashPlayTheme.color("panel"),ink:HashPlayTheme.color("ink"),muted:HashPlayTheme.color("muted")})');
  if(state.theme!==theme||state.unit!=='0.37'||state.pressed!==1||state.hit===state.selected)throw Error('主题切换影响状态或缺少区分 '+theme);
  if(ratio(state.panel,state.ink)<7||ratio(state.panel,state.muted)<4.5)throw Error('主题文字对比度不足 '+theme);
  const badge=await run('(function(){const c=document.createElement("canvas").getContext("2d"),toHex=v=>{c.fillStyle=v;c.fillRect(0,0,1,1);return "#"+[...c.getImageData(0,0,1,1).data].slice(0,3).map(n=>n.toString(16).padStart(2,"0")).join("")},s=getComputedStyle(document.querySelector(".paper-ledger .st-pill.hit"));return {ink:toHex(s.color),bg:toHex(s.backgroundColor)}})()');
  if(ratio(badge.ink,badge.bg)<4.5)throw Error('命中高亮对比度不足 '+theme);
  backgrounds.push(state.bg);contrast.push({theme,text:ratio(state.panel,state.ink),secondary:ratio(state.panel,state.muted),hit:ratio(badge.ink,badge.bg)});
  await shot('theme-'+theme);
 }
 if(new Set(backgrounds).size!==7)throw Error('主题背景未区分');
 const actualStrong=await run('getComputedStyle(document.querySelector(".paper-ledger .st-pill.hit")).boxShadow');
 const strong=await run('getComputedStyle(document.querySelector(".hp-theme-samples .hp-hit")).boxShadow');
 await run('document.querySelector("#hp-theme-emphasis").click()');
 const normal=await run('getComputedStyle(document.querySelector(".hp-theme-samples .hp-hit")).boxShadow');
 if(strong===normal)throw Error('增强高亮无变化');
 if(actualStrong===await run('getComputedStyle(document.querySelector(".paper-ledger .st-pill.hit")).boxShadow'))throw Error('真实账本高亮无变化');
 await run('document.querySelector("#hp-theme-close").click()');
 await run('document.querySelector("#paper-bots").scrollIntoView({block:"start"})');await shot('theme-exchange-ledger');
 await win.reload();await wait('!!document.querySelector("#hp-theme-dialog")');
 if(!await run('document.documentElement.dataset.theme==="exchange" && document.documentElement.dataset.emphasis==="normal"'))throw Error('主题刷新后丢失');
 await win.loadURL('hashplay://app/analysis?source=qkltj:6002');await wait('!!window.echarts && !!window.Chart && !!document.querySelector("#hp-theme-dialog")');
 if(!await run('document.documentElement.dataset.theme==="exchange"'))throw Error('跨页面主题丢失');
 const charts=await run("(function(){\n const el=document.createElement('div');el.style.cssText='width:400px;height:200px';document.body.append(el);\n const c=HashPlayTheme.echarts(echarts.init(el));c.setOption({xAxis:{type:'category',data:['a','b','c']},yAxis:{type:'value'},dataZoom:[{type:'inside',start:0,end:100}],series:[{type:'line',data:[1,2,3]}]});\n c.dispatchAction({type:'dataZoom',start:35,end:80});\n const canvas=document.createElement('canvas');document.body.append(canvas);\n const jc=HashPlayTheme.chart(new Chart(canvas,{type:'line',data:{labels:['a','b'],datasets:[{data:[2,4]}]},options:{animation:false}}));\n HashPlayTheme.apply({theme:'cyber',emphasis:true});\n const o=c.getOption(),ok=o.dataZoom[0].start===35 && o.dataZoom[0].end===80 && o.series[0].data[2]===3 && o.xAxis[0].axisLabel.color===HashPlayTheme.color('muted') && jc.data.datasets[0].data[1]===4 && jc.options.scales.x.ticks.color===HashPlayTheme.color('muted');\n c.dispose();el.remove();jc.destroy();canvas.remove();return ok;\n})()");
 if(!charts)throw Error('换色改变图表数据或缩放');
 await win.loadURL('hashplay://app/simulator?source=qkltj:6002');await wait('!!document.querySelector("#p-unit") && !!document.querySelector("#hp-theme-dialog")');
 await run('document.querySelector("#paper-bots").scrollIntoView({block:"start"})');await shot('theme-cyber-ledger');
 win.setMinimumSize(360,600);win.setSize(420,900);await delay(200);
 await run('document.querySelector("#hp-theme-toggle").click()');await shot('theme-mobile');
 if(await run('document.documentElement.scrollWidth>innerWidth+1 || document.querySelector("#hp-theme-dialog").scrollWidth>document.querySelector("#hp-theme-dialog").clientWidth+1'))throw Error('主题面板窄屏溢出');
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});
 await wait('!document.querySelector("#hp-theme-dialog").open');
 if(!await run('document.activeElement.id==="hp-theme-toggle"'))throw Error('关闭主题面板后焦点丢失');
 win.setSize(1360,920);win.setMinimumSize(1050,700);
 await run('HashPlayTheme.apply({theme:"warm",emphasis:true});document.querySelector("#p-unit").value='+JSON.stringify(original));
 result.themes={count:7,instantPreview:true,formPreserved:true,persistent:true,selectionAndHitDistinct:true,emphasis:true,chartsPreserved:true,keyboard:true,mobileNoOverflow:true,contrast};
};
